[package]
name = "webhook"
version = "0.1.0"
edition = "2024"

[dependencies]
frankenstein = { version = "0.44.0", features = ["client-ureq"] }
dotenvy = "0.15.7"
clap = { version = "4.5.43", features = ["derive"] }
rcgen = "0.14.3"
