[package]
name = "symtree"
version = "0.1.0"
edition = "2024"

[dependencies]
indoc = "2.0.6"
serde = { version = "1.0.219", features = ["derive"] }
ascase = { path = "../ascase" }
codepoint = { path = "../codepoint" }
