[package]
name = "telegram"
version = "0.1.0"
edition = "2024"

[dependencies.serde_json]
version = "1.0.143"

[dependencies.reqwest]
version = "0.12.23"
features = ["rustls-tls", "multipart"]
default-features = false

[dependencies.serde]
version = "1.0.219"
features = ["derive"]
